### ISSUE TITLE
Tracking issue for Coroutine

### ISSUE THREAD

**Issue by HoshinoTented** [HoshinoTented/HoshiNoMagic#9]
Cause that the HNM **ONLY** supports the Single Thread Model currently, so we maybe need to provide a (built-in) coroutine (like Lua).

**Comment by HoshinoTented** [comment]
However, HNM maybe supports multithreading in the future...

**Comment by chuigda** [comment]
Should we make a stackful or stackless one?

**Comment by HoshinoTented** [comment]
i want a stackless one

**Comment by chuigda** [comment]
And I have that knowledge~
